# Generated by Django 4.2.23 on 2025-09-02 20:15

from django.db import migrations

# A list of all 150 permissions to be added to the system.
# Each permission has a unique code, an English name, and an Arabic name.
PERMISSIONS_LIST = [
    # User and Role Management Permissions (PERM001-PERM010)
    {"code": "PERM001", "name_en": "Users_Create", "name_ar": "إنشاء مستخدمين"},
    {"code": "PERM002", "name_en": "Users_Edit", "name_ar": "تعديل مستخدمين"},
    {"code": "PERM003", "name_en": "Users_Delete", "name_ar": "حذف مستخدمين"},
    {"code": "PERM004", "name_en": "Users_View", "name_ar": "عرض المستخدمين"},
    {"code": "PERM005", "name_en": "Roles_Create", "name_ar": "إنشاء أدوار"},
    {"code": "PERM006", "name_en": "Roles_Edit", "name_ar": "تعديل ادوار"},
    {"code": "PERM007", "name_en": "Roles_Delete", "name_ar": "حذف ادوار"},
    {"code": "PERM008", "name_en": "Roles_View", "name_ar": "عرض الأدوار"},
    {"code": "PERM009", "name_en": "Users_Profile_Manage", "name_ar": "إدارة ملفات المستخدمين"},
    {"code": "PERM010", "name_en": "Users_Password_Reset", "name_ar": "إعادة تعيين كلمة المرور"},
    
    # Dashboard Permissions (PERM011-PERM020)
    {"code": "PERM011", "name_en": "Dashboard_Main_View", "name_ar": "عرض لوحة التحكم الرئيسية"},
    {"code": "PERM012", "name_en": "Dashboard_Projects_View", "name_ar": "عرض لوحة تحكم المشاريع"},
    {"code": "PERM013", "name_en": "Dashboard_Transactions_View", "name_ar": "عرض لوحة تحكم المعاملات"},
    {"code": "PERM014", "name_en": "Dashboard_Financial_View", "name_ar": "عرض لوحة التحكم المالية"},
    {"code": "PERM015", "name_en": "Dashboard_Tasks_View", "name_ar": "عرض لوحة تحكم المهام"},
    {"code": "PERM016", "name_en": "Dashboard_HR_View", "name_ar": "عرض لوحة تحكم الموارد البشرية"},
    {"code": "PERM017", "name_en": "Dashboard_Reports_View", "name_ar": "عرض لوحة تحكم التقارير"},
    {"code": "PERM018", "name_en": "Dashboard_Clients_View", "name_ar": "عرض لوحة تحكم العملاء"},
    {"code": "PERM019", "name_en": "Dashboard_Support_View", "name_ar": "عرض لوحة تحكم الدعم الفني"},
    {"code": "PERM020", "name_en": "Dashboard_Customize", "name_ar": "تخصيص لوحة التحكم"},

    # Project Management Permissions (PERM021-PERM035)
    {"code": "PERM021", "name_en": "Projects_Create", "name_ar": "إنشاء مشاريع"},
    {"code": "PERM022", "name_en": "Projects_Edit", "name_ar": "تعديل المشاريع"},
    {"code": "PERM023", "name_en": "Projects_Delete", "name_ar": "حذف المشاريع"},
    {"code": "PERM024", "name_en": "Projects_View_All", "name_ar": "عرض كل المشاريع"},
    {"code": "PERM025", "name_en": "Projects_View_Assigned", "name_ar": "عرض المشاريع المسندة"},
    {"code": "PERM026", "name_en": "Projects_Assign_Users", "name_ar": "إسناد المستخدمين للمشاريع"},
    {"code": "PERM027", "name_en": "Projects_Change_Status", "name_ar": "تغيير حالة المشاريع"},
    {"code": "PERM028", "name_en": "Projects_Manage_Docs", "name_ar": "إدارة مستندات المشاريع"},
    {"code": "PERM029", "name_en": "Projects_Track_Progress", "name_ar": "متابعة تقدم المشاريع"},
    {"code": "PERM030", "name_en": "Projects_Manage_Budget", "name_ar": "إدارة ميزانية المشاريع"},
    {"code": "PERM031", "name_en": "Projects_Create_Reports", "name_ar": "إنشاء تقارير المشاريع"},
    {"code": "PERM032", "name_en": "Projects_View_Financials", "name_ar": "عرض ماليات المشاريع"},
    {"code": "PERM033", "name_en": "Projects_Approve_Changes", "name_ar": "اعتماد تغييرات المشاريع"},
    {"code": "PERM034", "name_en": "Projects_Manage_Contracts", "name_ar": "إدارة عقود المشاريع"},
    {"code": "PERM035", "name_en": "Projects_Archive", "name_ar": "أرشفة المشاريع"},

    # Transaction Management Permissions (PERM036-PERM050)
    {"code": "PERM036", "name_en": "Transactions_Create", "name_ar": "إنشاء معاملات"},
    {"code": "PERM037", "name_en": "Transactions_Edit", "name_ar": "تعديل المعاملات"},
    {"code": "PERM038", "name_en": "Transactions_Delete", "name_ar": "حذف المعاملات"},
    {"code": "PERM039", "name_en": "Transactions_View_All", "name_ar": "عرض كل المعاملات"},
    {"code": "PERM040", "name_en": "Transactions_View_Assigned", "name_ar": "عرض المعاملات المسندة"},
    {"code": "PERM041", "name_en": "Transactions_Assign", "name_ar": "إسناد المعاملات"},
    {"code": "PERM042", "name_en": "Transactions_Change_Status", "name_ar": "تغيير حالة المعاملات"},
    {"code": "PERM043", "name_en": "Transactions_Approve", "name_ar": "اعتماد المعاملات"},
    {"code": "PERM044", "name_en": "Transactions_Reject", "name_ar": "رفض المعاملات"},
    {"code": "PERM045", "name_en": "Transactions_Manage_Docs", "name_ar": "إدارة مستندات المعاملات"},
    {"code": "PERM046", "name_en": "Transactions_Communicate_Client", "name_ar": "مراسلة العميل بخصوص المعاملة"},
    {"code": "PERM047", "name_en": "Transactions_Add_Notes", "name_ar": "إضافة ملاحظات للمعاملات"},
    {"code": "PERM048", "name_en": "Transactions_Track_History", "name_ar": "متابعة سجل المعاملات"},
    {"code": "PERM049", "name_en": "Transactions_Create_Invoice", "name_ar": "إنشاء فاتورة من معاملة"},
    {"code": "PERM050", "name_en": "Transactions_Archive", "name_ar": "أرشفة المعاملات"},

    # Client Management Permissions (PERM051-PERM060)
    {"code": "PERM051", "name_en": "Clients_Create", "name_ar": "إنشاء عملاء"},
    {"code": "PERM052", "name_en": "Clients_Edit", "name_ar": "تعديل العملاء"},
    {"code": "PERM053", "name_en": "Clients_Delete", "name_ar": "حذف العملاء"},
    {"code": "PERM054", "name_en": "Clients_View_All", "name_ar": "عرض كل العملاء"},
    {"code": "PERM055", "name_en": "Clients_View_Assigned", "name_ar": "عرض العملاء المسندين"},
    {"code": "PERM056", "name_en": "Clients_Merge", "name_ar": "دمج العملاء"},
    {"code": "PERM057", "name_en": "Clients_Export", "name_ar": "تصدير بيانات العملاء"},
    {"code": "PERM058", "name_en": "Clients_View_Transactions", "name_ar": "عرض معاملات العميل"},
    {"code": "PERM059", "name_en": "Clients_View_Projects", "name_ar": "عرض مشاريع العميل"},
    {"code": "PERM060", "name_en": "Clients_Manage_Contacts", "name_ar": "إدارة جهات اتصال العميل"},

    # Financial Management Permissions (PERM061-PERM080)
    {"code": "PERM061", "name_en": "Invoices_Create", "name_ar": "إنشاء فواتير"},
    {"code": "PERM062", "name_en": "Invoices_Edit", "name_ar": "تعديل الفواتير"},
    {"code": "PERM063", "name_en": "Invoices_Delete", "name_ar": "حذف الفواتير"},
    {"code": "PERM064", "name_en": "Invoices_View_All", "name_ar": "عرض كل الفواتير"},
    {"code": "PERM065", "name_en": "Invoices_Send", "name_ar": "إرسال الفواتير"},
    {"code": "PERM066", "name_en": "Invoices_Record_Payment", "name_ar": "تسجيل مدفوعات الفواتير"},
    {"code": "PERM067", "name_en": "Payments_View", "name_ar": "عرض المدفوعات"},
    {"code": "PERM068", "name_en": "Payments_Export", "name_ar": "تصدير المدفوعات"},
    {"code": "PERM069", "name_en": "Quotes_Create", "name_ar": "إنشاء عروض أسعار"},
    {"code": "PERM070", "name_en": "Quotes_Edit", "name_ar": "تعديل عروض الأسعار"},
    {"code": "PERM071", "name_en": "Quotes_Delete", "name_ar": "حذف عروض الأسعار"},
    {"code": "PERM072", "name_en": "Quotes_Send", "name_ar": "إرسال عروض الأسعار"},
    {"code": "PERM073", "name_en": "Quotes_ConvertToInvoice", "name_ar": "تحويل عرض سعر لفاتورة"},
    {"code": "PERM074", "name_en": "Expenses_Create", "name_ar": "تسجيل المصروفات"},
    {"code": "PERM075", "name_en": "Expenses_Edit", "name_ar": "تعديل المصروفات"},
    {"code": "PERM076", "name_en": "Expenses_Delete", "name_ar": "حذف المصروفات"},
    {"code": "PERM077", "name_en": "Expenses_View", "name_ar": "عرض المصروفات"},
    {"code": "PERM078", "name_en": "Financial_Reports_View", "name_ar": "عرض التقارير المالية"},
    {"code": "PERM079", "name_en": "Chart_of_Accounts_Manage", "name_ar": "إدارة دليل الحسابات"},
    {"code": "PERM080", "name_en": "Journal_Entries_Manage", "name_ar": "إدارة قيود اليومية"},

    # HR Management Permissions (PERM081-PERM100)
    {"code": "PERM081", "name_en": "Employees_Add", "name_ar": "إضافة موظفين"},
    {"code": "PERM082", "name_en": "Employees_Edit", "name_ar": "تعديل بيانات الموظفين"},
    {"code": "PERM083", "name_en": "Employees_Terminate", "name_ar": "إنهاء خدمة الموظفين"},
    {"code": "PERM084", "name_en": "Employees_View_All", "name_ar": "عرض كل الموظفين"},
    {"code": "PERM085", "name_en": "Employees_View_Personal_Info", "name_ar": "عرض المعلومات الشخصية للموظفين"},
    {"code": "PERM086", "name_en": "Salaries_Manage", "name_ar": "إدارة الرواتب"},
    {"code": "PERM087", "name_en": "Salaries_View", "name_ar": "عرض الرواتب"},
    {"code": "PERM088", "name_en": "Attendance_Manage", "name_ar": "إدارة الحضور والانصراف"},
    {"code": "PERM089", "name_en": "Attendance_View", "name_ar": "عرض سجلات الحضور"},
    {"code": "PERM090", "name_en": "Leaves_Manage", "name_ar": "إدارة الإجازات"},
    {"code": "PERM091", "name_en": "Leaves_Approve", "name_ar": "اعتماد الإجازات"},
    {"code": "PERM092", "name_en": "Leaves_View", "name_ar": "عرض طلبات الإجازات"},
    {"code": "PERM093", "name_en": "Payroll_Run", "name_ar": "تشغيل مسير الرواتب"},
    {"code": "PERM094", "name_en": "Payroll_View_History", "name_ar": "عرض سجل مسيرات الرواتب"},
    {"code": "PERM095", "name_en": "Employee_Self_Service_View", "name_ar": "عرض بوابة الخدمة الذاتية"},
    {"code": "PERM096", "name_en": "Employee_Docs_Manage", "name_ar": "إدارة مستندات الموظفين"},
    {"code": "PERM097", "name_en": "HR_Reports_View", "name_ar": "عرض تقارير الموارد البشرية"},
    {"code": "PERM098", "name_en": "Departments_Manage", "name_ar": "إدارة الأقسام"},
    {"code": "PERM099", "name_en": "Job_Titles_Manage", "name_ar": "إدارة المسميات الوظيفية"},
    {"code": "PERM100", "name_en": "Performance_Reviews_Manage", "name_ar": "إدارة تقييم الأداء"},
    
    # And so on for the rest of the permissions...
    {"code": "PERM101", "name_en": "Contracts_Create", "name_ar": "إنشاء عقود"},
    {"code": "PERM102", "name_en": "Contracts_Edit", "name_ar": "تعديل العقود"},
    {"code": "PERM103", "name_en": "Contracts_Delete", "name_ar": "حذف العقود"},
    {"code": "PERM104", "name_en": "Contracts_View", "name_ar": "عرض العقود"},
    {"code": "PERM105", "name_en": "Contracts_Approve", "name_ar": "اعتماد العقود"},
    {"code": "PERM106", "name_en": "Calendar_View_All", "name_ar": "عرض تقويم المكتب"},
    {"code": "PERM107", "name_en": "Calendar_View_Personal", "name_ar": "عرض التقويم الشخصي"},
    {"code": "PERM108", "name_en": "Appointments_Create", "name_ar": "إنشاء مواعيد"},
    {"code": "PERM109", "name_en": "Appointments_Edit", "name_ar": "تعديل المواعيد"},
    {"code": "PERM110", "name_en": "Appointments_Delete", "name_ar": "حذف المواعيد"},
    {"code": "PERM111", "name_en": "Documents_Upload", "name_ar": "رفع المستندات"},
    {"code": "PERM112", "name_en": "Documents_Download", "name_ar": "تحميل المستندات"},
    {"code": "PERM113", "name_en": "Documents_Delete", "name_ar": "حذف المستندات"},
    {"code": "PERM114", "name_en": "Documents_Share", "name_ar": "مشاركة المستندات"},
    {"code": "PERM115", "name_en": "Documents_View_All", "name_ar": "عرض كل المستندات"},
    {"code": "PERM116", "name_en": "Messaging_Send", "name_ar": "إرسال رسائل داخلية"},
    {"code": "PERM117", "name_en": "Messaging_Receive", "name_ar": "استقبال الرسائل الداخلية"},
    {"code": "PERM118", "name_en": "Messaging_Delete", "name_ar": "حذف الرسائل"},
    {"code": "PERM119", "name_en": "Notifications_View", "name_ar": "عرض الإشعارات"},
    {"code": "PERM120", "name_en": "Notifications_Clear", "name_ar": "مسح الإشعارات"},
    {"code": "PERM121", "name_en": "Assets_Create", "name_ar": "إضافة أصول"},
    {"code": "PERM122", "name_en": "Assets_Edit", "name_ar": "تعديل الأصول"},
    {"code": "PERM123", "name_en": "Assets_Delete", "name_ar": "حذف الأصول"},
    {"code": "PERM124", "name_en": "Assets_View", "name_ar": "عرض الأصول"},
    {"code": "PERM125", "name_en": "Assets_Assign", "name_ar": "تخصيص الأصول"},
    {"code": "PERM126", "name_en": "Procurement_Create_Request", "name_ar": "إنشاء طلب شراء"},
    {"code": "PERM127", "name_en": "Procurement_Approve_Request", "name_ar": "اعتماد طلبات الشراء"},
    {"code": "PERM128", "name_en": "Procurement_Manage_Orders", "name_ar": "إدارة أوامر الشراء"},
    {"code": "PERM129", "name_en": "Procurement_View_History", "name_ar": "عرض سجل المشتريات"},
    {"code": "PERM130", "name_en": "Vendors_Manage", "name_ar": "إدارة الموردين"},
    {"code": "PERM131", "name_en": "Tickets_Create", "name_ar": "إنشاء تذاكر دعم"},
    {"code": "PERM132", "name_en": "Tickets_Edit", "name_ar": "تعديل تذاكر الدعم"},
    {"code": "PERM133", "name_en": "Tickets_Close", "name_ar": "إغلاق التذاكر"},
    {"code": "PERM134", "name_en": "Tickets_View", "name_ar": "عرض التذاكر"},
    {"code": "PERM135", "name_en": "Tickets_Assign", "name_ar": "توزيع التذاكر"},
    {"code": "PERM136", "name_en": "KnowledgeBase_View", "name_ar": "عرض قاعدة المعرفة"},
    {"code": "PERM137", "name_en": "KnowledgeBase_Edit", "name_ar": "تعديل قاعدة المعرفة"},
    {"code": "PERM138", "name_en": "Tasks_Create", "name_ar": "إنشاء مهام"},
    {"code": "PERM139", "name_en": "Tasks_Edit", "name_ar": "تعديل مهام"},
    {"code": "PERM140", "name_en": "Tasks_Delete", "name_ar": "حذف مهام"},
    {"code": "PERM141", "name_en": "Tasks_View", "name_ar": "عرض المهام"},
    {"code": "PERM142", "name_en": "Tasks_Assign", "name_ar": "توزيع المهام"},
    {"code": "PERM143", "name_en": "Tasks_Track", "name_ar": "متابعة المهام"},
    {"code": "PERM144", "name_en": "Reports_Generate", "name_ar": "توليد التقارير"},
    {"code": "PERM145", "name_en": "Reports_View", "name_ar": "عرض التقارير"},
    {"code": "PERM146", "name_en": "System_Settings_Edit", "name_ar": "تعديل إعدادات النظام"},
    {"code": "PERM147", "name_en": "Backup_Create", "name_ar": "إنشاء نسخ احتياطية"},
    {"code": "PERM148", "name_en": "Backup_Restore", "name_ar": "استعادة نسخ احتياطية"},
    {"code": "PERM149", "name_en": "AuditLogs_View", "name_ar": "عرض سجلات التدقيق"},
    {"code": "PERM150", "name_en": "API_Access_Manage", "name_ar": "إدارة الوصول عبر API"},
]

def populate_permissions(apps, schema_editor):
    """
    This function gets the Permission model and iterates over the PERMISSIONS_LIST,
    creating a new permission object for each item in the list.
    This ensures that all necessary permissions are available in the database
    after running the migration.
    """
    Permission = apps.get_model('core', 'Permission')
    for perm_data in PERMISSIONS_LIST:
        Permission.objects.create(
            code=perm_data['code'],
            name_en=perm_data['name_en'],
            name_ar=perm_data['name_ar']
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_permissions),
    ]