# Generated by Django 4.2.23 on 2025-09-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_populate_permissions'),
        ('core', '0003_populate_initial_data'),
    ]

    operations = [
    ]
