# Generated by Django 4.2.23 on 2025-09-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_populate_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='qr_code_image',
            field=models.TextField(blank=True, null=True, verbose_name='QR Code Image (Base64)'),
        ),
    ]
