# Generated by Django 4.2.23 on 2025-09-04 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invoice_qr_code_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('north_desc_nature', models.CharField(blank=True, max_length=255, verbose_name='وصف الحد الشمالي طبيعة')),
                ('north_length_nature', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='طول الحد الشمالي طبيعة')),
                ('east_desc_nature', models.CharField(blank=True, max_length=255, verbose_name='وصف الحد الشرقي طبيعة')),
                ('east_length_nature', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='طول الحد الشرقي طبيعة')),
                ('south_desc_nature', models.CharField(blank=True, max_length=255, verbose_name='وصف الحد الجنوبي طبيعة')),
                ('south_length_nature', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='طول الحد الجنوبي طبيعة')),
                ('west_desc_nature', models.CharField(blank=True, max_length=255, verbose_name='وصف الحد الغربي طبيعة')),
                ('west_length_nature', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='طول الحد الغربي طبيعة')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='core.transaction')),
            ],
        ),
    ]
