# Generated by Django 4.2.23 on 2025-09-04 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name_ar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('missing', 'مطلوب'), ('uploaded', 'تم الرفع'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='missing', max_length=20)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.documenttype')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='core.transaction')),
                ('uploaded_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.document')),
            ],
            options={
                'unique_together': {('transaction', 'document_type')},
            },
        ),
    ]
