# Generated by Django 4.2.23 on 2025-09-05 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_populate_document_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondocument',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='document',
            name='transaction_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.transactiondocument'),
        ),
    ]
