# Generated by Django 4.2.23 on 2025-09-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_transactiondocument_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('PLAN_REVIEW', 'تدقيق مخطط'), ('DOC_REVIEW', 'مراجعة مستندات'), ('TECH_REPORT', 'إعداد تقرير فني'), ('EXT_FOLLOW', 'متابعة معاملة خارجية'), ('ACC_AUDIT', 'تدقيق حسابات'), ('QUOTE_PREP', 'إعداد عرض سعر'), ('DATA_UPDATE', 'تحديث بيانات'), ('GENERAL_TASK', 'مهمة عامة')], default='GENERAL_TASK', max_length=20, verbose_name='نوع المهمة'),
        ),
    ]
