# Generated by Django 4.2.23 on 2025-09-05 16:34

from django.db import migrations

DEPARTMENTS_LIST = [
    "الهندسة",
    "الإدارة",
    "المحاسبة",
    "الموارد البشرية",
    "التسويق",
]

def populate_departments(apps, schema_editor):
    Department = apps.get_model('core', 'Department')
    for dept_name in DEPARTMENTS_LIST:
        Department.objects.get_or_create(name=dept_name)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_department_field'),
    ]

    operations = [
        migrations.RunPython(populate_departments),
    ]