# Generated by Django 4.2.23 on 2025-09-06 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_populate_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المبلغ الإجمالي للميزانية')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='الإصدار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
            ],
            options={
                'verbose_name': 'ميزانية',
                'verbose_name_plural': 'الميزانيات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المشروع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المشروع')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('PENDING', 'معلق'), ('IN_PROGRESS', 'قيد التنفيذ'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغي')], default='PENDING', max_length=20, verbose_name='حالة المشروع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.client', verbose_name='العميل')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='مدير المشروع')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='core.transaction', verbose_name='المعاملة المرتبطة')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LABOR', 'أعمال'), ('MATERIALS', 'مواد'), ('PERMITS', 'تراخيص ورسوم'), ('EQUIPMENT', 'معدات'), ('SUBCONTRACTOR', 'مقاول باطن'), ('OTHER', 'أخرى')], max_length=50, verbose_name='فئة البند')),
                ('description', models.CharField(max_length=255, verbose_name='وصف البند')),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='التكلفة التقديرية')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='التكلفة الفعلية')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.budget', verbose_name='الميزانية')),
            ],
            options={
                'verbose_name': 'بند ميزانية',
                'verbose_name_plural': 'بنود الميزانية',
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='core.project', verbose_name='المشروع'),
        ),
    ]
