# Generated by Django 4.2.23 on 2025-09-06 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_conversation_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField(verbose_name='المبرر')),
                ('status', models.CharField(choices=[('PENDING', 'معلق'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20, verbose_name='حالة الطلب')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permission', verbose_name='الصلاحية المطلوبة')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_permission_requests', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
            ],
            options={
                'verbose_name': 'طلب صلاحية',
                'verbose_name_plural': 'طلبات الصلاحيات',
                'ordering': ['-created_at'],
            },
        ),
    ]
