# Generated by Django 4.2.23 on 2025-09-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_permissionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_stamped',
            field=models.BooleanField(default=False, verbose_name='هل تم الختم؟'),
        ),
        migrations.AddField(
            model_name='document',
            name='stamped_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/stamped/', verbose_name='الملف المختوم'),
        ),
    ]
