# Generated by Django 4.2.23 on 2025-09-07 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('ANNUAL', 'إجازة سنوية'), ('SICK', 'إجازة مرضية'), ('EMERGENCY', 'إجازة طارئة'), ('UNPAID', 'إجازة بدون راتب'), ('OTHER', 'أخرى')], max_length=20, verbose_name='نوع الإجازة')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('status', models.CharField(choices=[('PENDING', 'معلق'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
            ],
            options={
                'verbose_name': 'طلب إجازة',
                'verbose_name_plural': 'طلبات الإجازات',
                'ordering': ['-created_at'],
            },
        ),
    ]
