# Generated by Django 4.2.23 on 2025-09-08 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_permission_code_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('manager_notes', models.TextField(blank=True, null=True)),
                ('employee_notes', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_assignments', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='core.transaction')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
