# Generated by Django 4.2.23 on 2025-09-09 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_transactiondistribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
