# Generated by Django 4.2.23 on 2025-09-11 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0029_userpresence_chatroom_chatmessage_messagereadstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'إشعار', 'verbose_name_plural': 'الإشعارات'},
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('NEW_TASK', 'مهمة جديدة'), ('STATUS_CHANGE', 'تغيير حالة'), ('NEW_MESSAGE', 'رسالة جديدة'), ('PERMISSION_REQUEST', 'طلب صلاحية'), ('PERMISSION_RESPONSE', 'رد على طلب صلاحية'), ('TRANSACTION_ASSIGNED', 'إسناد معاملة'), ('GENERIC_NOTIFICATION', 'إشعار عام')], default='GENERIC_NOTIFICATION', max_length=50, verbose_name='نوع الحدث'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='مقروء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
