# Generated by Django 4.2.23 on 2025-09-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_notification_options_notification_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف المعاملة'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='engineering_discipline',
            field=models.CharField(choices=[('ARCH', 'معماري'), ('STRU', 'إنشائي'), ('ELEC', 'كهربائي'), ('MECH', 'ميكانيكي'), ('CIVL', 'مدني'), ('ENV', 'بيئي')], default='ARCH', max_length=10, verbose_name='التخصص الهندسي'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='expected_duration',
            field=models.PositiveIntegerField(blank=True, help_text='المدة بالأيام', null=True, verbose_name='المدة الزمنية المتوقعة'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='expected_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البدء المتوقع'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الموقع الجغرافي'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(default='بدون عنوان', max_length=255, verbose_name='عنوان المعاملة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='short_code',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True, verbose_name='رمز المعاملة'),
        ),
    ]
