# Generated by Django 4.2.23 on 2025-09-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_transaction_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sub_specialization',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='التخصص الفرعي'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.CharField(editable=False, help_text='يتم إنشاؤه تلقائيًا. مثال: CL-P-2025-00001', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('P', 'شخص طبيعي'), ('C', 'شركة خاصة'), ('G', 'جهة حكومية'), ('E', 'مكتب هندسي'), ('R', 'مقاول'), ('D', 'مطور عقاري'), ('I', 'منظمة دولية'), ('N', 'جمعية خيرية')], default='P', max_length=20, verbose_name='نوع العميل'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name_ar',
            field=models.CharField(max_length=255, verbose_name='اسم العميل بالعربية'),
        ),
    ]
